### ISSUE TITLE
Error: Cannot run with sound null safety, because the following dependencies

### ISSUE THREAD

**Issue by AndroidIosWebEmbeddedFirmwareDver** [billylev/flutter_localizations#5]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:flutter_localizations

- package:intl

For solutions, see https://dart.dev/go/unsound-null-safety

**Comment by tjerkw** [comment]
Same problem, i cannot build my app anymore

Because every version of flutter_localizations from sdk depends on path 1.8.0-nullsafety.3 and intl >=0.17.0 depends on path ^1.8.0, flutter_localizations from sdk is incompatible with intl >=0.17.0.
So, because boomrang_app depends on both flutter_localizations any from sdk and intl ^0.17.0, version solving failed.

**Comment by billylev** [comment]
Upgraded project to Flutter 2, with sound null safety.
